using System.Collections.Generic;
using Scripts.Main;
using UnityEngine;

namespace Bourg.Achetable
{

    public class Murs : Achetables
    {
        //TODO: Recursive Neighbours Search
    }
}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        